### ISSUE TITLE
Replace 5 minute sleep in deploy (waiting for the docker image) with polling

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/folio-graphql#135]

**Comment by marlo-longley** [comment]
I had been working on this approach with Cory last year.
https://github.com/sul-dlss/folio-graphql/pull/139

It's been a minute so I would need to get the test setup running again to make sure all still works. My fault for not linking the issue.

**Comment by marlo-longley** [comment]
I have a solution that will work for tagged production releases. It checks if the tag vX.X.X exists in the Docker Hub and when it does, proceeds. This won't work for staging releases because the Docker Hub tag we use for that deploy is `main` -- the image is always tagged main, but the internals of that image get updated. Checking to see if the `main` tag exists in the same way we do for the latest vX.X.X release doesn't make sense - it will always exist, and we can't easily check if it has changed without downloading it and doing a complicated comparison of the contents of the image digest.

I'd love to use this plugin: https://plugins.jenkins.io/dockerhub-notification/ -- we could trigger a build using a webhook when an image changes. However it requires Jenkins 2.414.3. We are on 2.414.1.

**Comment by hudajkhan** [comment]
Possibly need to upgrade Jenkins to help with this process.

**Comment by cbeer** [comment]
Jenkins on sul-ci-prod is now on 2.426.3.

**Comment by marlo-longley** [comment]
Update: sent this message to the Ops slack channel. Awaiting advice.

> I am looking to let Dockerhub webhooks through security of our Jenkins server. With Github for example we whitelist IPs:
> https://github.com/sul-dlss/puppet/blob/53687bf6512499a695c13a7970eb0964cdb9470b/hieradata/common.eyaml#L479
> However I am reading that DockerHub doesn't have static IP that can be whitelisted, it's based on Amazon ELB, so they can change any time. I could be wrong about what this means, though.
> Currently my webhook approach is failing because it's hitting a login redirect on the Jenkins server (sul-ci-prod).
> Another approach could be to use something like https://containrrr.dev/watchtower/ but we'd need to install it on the servers.

**Comment by marlo-longley** [comment]
Update from team meeting: we think proceeding with the idea of a new proxy server is worthwhile here.

**Comment by marlo-longley** [comment]
Marlo request to Ops:

"webhook-proxy" -- no dev/test/prod?
add healthcheck API, look at it with nagios


provision a node server that is open to the public on 443
make it a docker deployment (like folio-graphql) 
no load balancing, not a ton of memory or disc space
