### ISSUE TITLE
Allow pagination for retrieving items/holdings for an instance

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/folio-graphql#184]

**Comment by dnoneill** [comment]
Due to trying sorting on the itemStatus, status field in folio-graphql not working we were not able to get the status field to sort which would have made it difficult to paginate the results in a way where we could determine hold/recall status. 

Also bib_data in the request model is called twice if there is a request option page (sending a request to folio twice). This should be fixed in rework but is not an easy fix now.

Closing as not fixing now.
